name: Docker Image CI for GHCR

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push the image
        run: |
          docker login --username kirpandu --password "${{ secrets.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}}"
          docker build -t ghcr.io/kirpandu/arithmetic-service:latest --file Dockerfile .
          docker push ghcr.io/kirpandu/arithmetic-service:latest
  login:
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.KirthivasanPN-hash }}
          password: ${{ secrets.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 }}
